M48
; DRILL file {KiCad 7.0.7} date 2023 September 13, Wednesday 19:57:04
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-13T19:57:04-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X104.0Y-44.0
X104.0Y-91.0
X150.0Y-67.0
X196.0Y-44.0
X196.0Y-91.0
T0
M30
